"dfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflk"
"dfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsldfjlksdlkjfsdlkjflksjdflkjsdljkfsdljflksdjflkdfskldfjsld"
" NUL"
long string
double line comments
"^@"
""
-- THis is a comments
did
